// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhefgkbsvjzitiuqoedd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoZWZna2Jzdmp6aXRpdXFvZWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDgzMjgsImV4cCI6MjA2MDEyNDMyOH0.7j-XOo8wpdJlkH4pwIeQMUaqUaWaq05o6erEnrGNbn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);